pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sebadelaf/Tingeso1']])
                dir("frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Fix Docker Context") { //adopta el contexto de mi pc
            steps {
                bat 'docker context use default'
            }
        } 
        stage("Build and Push Docker Image"){
            steps{
                dir("frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t sebadelaf10/frontend:latest ."
                            bat "docker push sebadelaf10/frontend:latest"
                        }
                    }                    
                }
            }
        }
    }
}