pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sebadelaf/Tingeso1']])
                dir("backend"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("backend"){
                    bat "mvn test"
                }
            }
        }
        stage("Fix Docker Context") {
            steps {
                bat 'docker context use default'
            }
        }        
        stage("Build and Push Docker Image"){
            steps{
                dir("backend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t sebadelaf10/backend:latest ."
                            bat "docker push sebadelaf10/backend:latest"
                        }
                    }                    
                }
            }
        }
    }
}