server:
  port: 0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_RMF2}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: 1234
  eureka:
    instance:
      preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/