server:
  port: 8079
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        # M1: tarifas-service (Controlador en /tarifas)
        - id: M1-tarifas-service
          uri: lb://tarifas-service
          predicates:
            - Path=/tarifas/**

        # M2: descuentos-grupo-service (Controlador en /descuentos-grupo)
        - id: M2-descuentos-grupo-service
          uri: lb://descuentos-grupo-service
          predicates:
            - Path=/descuentos-grupo/**

        # M3: descuentos-frecuentes-service (Controlador en /descuentos-frecuentes)
        - id: M3-descuentos-frecuentes-service
          uri: lb://descuentos-frecuentes-service
          predicates:
            - Path=/descuentos-frecuentes/**

        # M4: tarifas-especiales-service (Controlador en /tarifas-especiales)
        - id: M4-tarifas-especiales-service
          uri: lb://tarifas-especiales-service
          predicates:
            - Path=/tarifas-especiales/**

        # M5: reservas-comprobantes-service (Controlador Reserva en /reservas)
        - id: M5-reservas-service # Un id específico para las rutas de reservas
          uri: lb://reservas-comprobantes-service
          predicates:
            - Path=/reservas/**

        # M5: reservas-comprobantes-service (Controlador Comprobante en /comprobantes)
        - id: M5-comprobantes-service # Un id específico para las rutas de comprobantes
          uri: lb://reservas-comprobantes-service
          predicates:
            - Path=/comprobantes/**

        # M6: rack-pista-service (Controlador en /rack)
        - id: M6-rack-pista-service
          uri: lb://rack-pista-service
          predicates:
            - Path=/rack/**

        # M7: reportes-service (Controlador en /reportes)
        - id: M7-reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**