server:
  port: 0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_RFM5}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: sebastian.delafuente.c@usach.cl
    password: yqbd dwxr pzeh somr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}