server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rmf1
    username: postgres
    password: 1234
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/