apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  labels:
    app: gateway-server-deployment
spec:
  selector:
    matchLabels:
      app: gateway-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server-deployment
    spec:
      containers:
        - name: gateway-server
          image: sebadelaf10/gateway-server
          ports:
            - containerPort: 8079
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:${CONFIG_SERVER_URL}"
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: CONFIG_SERVER_URL
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE # Para que el gateway encuentre Eureka
              valueFrom:
                 configMapKeyRef:
                   name: app-configmap
                   key: EUREKA_SERVER_URL
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  labels:
    app: gateway-server-service
spec:
  selector:
    app: gateway-server-deployment
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
  type: LoadBalancer