apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-comprobantes-service-deployment
  labels:
    app: reservas-comprobantes-service # Etiqueta para este Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-comprobantes-service # Selector para los Pods gestionados por este Deployment
  template:
    metadata:
      labels:
        app: reservas-comprobantes-service # Etiqueta que tendrán los Pods
    spec:
      containers:
        - name: reservas-comprobantes-service
          image: sebadelaf10/reservas-comprobantes-service:latest

          ports:
            - containerPort: 8084
          env:


            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_URL_RFM5
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_USERNAME
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-comprobantes-service
  labels:
    app: reservas-comprobantes-service
spec:
  selector:
    app: reservas-comprobantes-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer