apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifas-service-deployment
  labels:
    app: tarifas-service # Etiqueta para este Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarifas-service # Selector para los Pods gestionados por este Deployment
  template:
    metadata:
      labels:
        app: tarifas-service # Etiqueta que tendrán los Pods
    spec:
      containers:
        - name: tarifas-service
          image: sebadelaf10/tarifas-service:latest
          ports:
            - containerPort: 8080 # Puerto donde el actuador podría estar o el puerto base de la app
          env:

            # Variables de la base de datos (tomadas del ConfigMap y Secret)
            - name: SPRING_DATASOURCE_URL # Spring Boot buscará esta variable
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_URL_RMF1 # Clave específica para la BD de tarifas-service
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_USERNAME
---
apiVersion: v1
kind: Service
metadata:
  name: tarifas-service # Nombre DNS para que otros servicios (como el Gateway) lo encuentren
  labels:
    app: tarifas-service # Etiqueta para este Service
spec:
  selector:
    app: tarifas-service # Debe coincidir con la etiqueta de los Pods del Deployment
  ports:
    - protocol: TCP
      port: 8080
      # El Gateway se comunicará con tarifas-service:80 (o solo tarifas-service si usa Eureka lb)
      targetPort: 8080
  type: LoadBalancer